# Generated by Django 5.0.1 on 2024-01-31 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('isbn', models.CharField(max_length=20)),
                ('published_date', models.DateField()),
                ('genre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Email', models.EmailField(default='default@gmail.com', max_length=254)),
                ('membership_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='BookDetails',
            fields=[
                ('details_id', models.AutoField(primary_key=True, serialize=False)),
                ('number_of_pages', models.IntegerField()),
                ('publisher', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=50)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Home.book')),
            ],
        ),
        migrations.CreateModel(
            name='BorrowedBooks',
            fields=[
                ('borrowed_books_id', models.AutoField(primary_key=True, serialize=False)),
                ('borrow_date', models.DateField()),
                ('return_date', models.DateField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.user')),
            ],
        ),
    ]
